---
- hosts: all
  become: true
  tasks:
      - name: Create partiton
        parted:
          device: "{{ item.device }}"
          number: "{{ item.number }}"
          part_end: "{{ item.end }}"
          part_start: "{{ item.start }}"
          state: present
#          part_type: logical
        with_items:
          - { device: "/dev/vdc", number: "1", start:  "0%", end:  "50GiB" }
          - { device: "/dev/vdc", number: "2", start:  "51GiB", end: "100GiB" }
          - { device: "/dev/vdc", number: "3", start: "101GiB", end: "100%" }
