---
- hosts: all
  become: true
  tasks:
        - name: Install required packages
          apt: name={{ item }} state=present
          with_items:
           - sysstat
           - gnuplot
           - bc
           - ntp
           - jq
           - parted
